### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by stephenajulu** [artemsheludko/zolan#1]
Hi, how are you?
Could you kindly add a dark theme. or button with the option to choose dark as primary.
Thank you.
This theme looks great!

**Comment by Dorson** [comment]
Custom colors would be very nice for the users :-)

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:
