### ISSUE TITLE
Tagging is going to 404 page

### ISSUE THREAD

**Issue by hmook** [artemsheludko/zolan#4]
Looks like there is something wrong with the tag-page. If I go to a tag page its going directly to the 404 page.

**Comment by artemsheludko** [comment]
@hmook 
Use the Netlify service to deploy so that the jekyll-tagging plugin works correctly.

**Comment by ungurnicoleta** [comment]
I have a problem with the share buttons that are at the end of a post. Thanks :)

**Comment by artemsheludko** [comment]
@ungurnicoleta What kind of problem?

**Comment by ungurnicoleta** [comment]
Well, It just says that the path is not working (the href). It happens also in the demo.
![Screenshot 2020-05-12 at 20 19 22](https://user-images.githubusercontent.com/32622785/81725017-ed414a00-948d-11ea-9391-8f9251df27ea.png)

Thank you for the fast response!

**Comment by artemsheludko** [comment]
@ungurnicoleta 

Just updated the demo link. Use the Netlify service to deploy and do not forget to specify the `url` in the `config.yml` file. Check it out https://zolan-jekyll.netlify.app/

**Comment by ungurnicoleta** [comment]
Cool, thanks :)
