### ISSUE TITLE
Footer typo & attribution.

### ISSUE THREAD

**Issue by ScottON** [artemsheludko/zolan#7]
Hey,

I'm loving the theme you created. 

I noticed that the footer has a typo in it: 'Power' instead of 'Powered'.

I also think you should add a link to your theme in there:

 `<div class="copyright">Copyright &copy; {{site.time | date: '%Y'}} <a href="/">{{ site.data.settings.title }}</a> — All right Reserved. Powered by <a href="https://jekyllrb.com/">Jekyll</a> & <a href ="https://github.com/artemsheludko/zolan">Zolan</a>.</div>`

Thanks,
Scott

**Comment by artemsheludko** [comment]
@ScottON Thanks a lot!
