### ISSUE TITLE
Feature Request: Sample Pages

### ISSUE THREAD

**Issue by ScottON** [artemsheludko/zolan#8]
Hey Artem,

I was just made redundant. As such, I've decided to try freelance writing. I'm focusing on job boards right now. In a few months, I want to build my website and try to generate inbound traffic. Your theme is EXACTLY how I want my site to look. 

I've got very limited web-design skills and I was hoping you'd be able to help me -and future users- out. 

I was hoping you'd be able to make a sample/template for:
    - Contact page - I think Netlify enables the forms to work?
    - [Portfolio page](https://www.graphicsegg.com/wp-content/uploads/2018/10/minimal%20portfolio%20html%20template/work.html)
    - [Service Page](https://www.graphicsegg.com/wp-content/uploads/2018/10/minimal%20portfolio%20html%20template/service.html)
    - [Testimonial template](https://bashooka.com/inspiration/testimonial-ui-design-examples/)
    - CTA buttons

The linked pages are just examples. Ideally, I'm wanting to create something like [this website](https://jacobmcmillen.com/homepage-copywriting-template/). That sort of idea but with your theme applied would be perfect! 

As I said, my web-design skills are very limited. I've no idea how much work this would take you. If I've just asked you to commit to a massive project for free, I apologise! I only have a limited budget which is why I'm looking at open source options. That being said, if it's a lot of work I'm open to making a donation.

Thanks for taking the time to read my request,
Scott

**Comment by artemsheludko** [comment]
Hey!

Unfortunately, I don't have much free time right now to deal with open source projects.

But if you're curious, I'm working on a similar portfolio theme right now, but this theme will be a premium one, and you can buy it at JekyllThemes.io.

Best wishes, Artem.

**Comment by ScottON** [comment]
Hey Artem,

Thanks for getting back to me so quickly.

Totally understandable.

There's a few nice themes on there! Once you've finished your portfolio theme please share a link to it specifically.

Thanks again,
Scott

**Comment by artemsheludko** [comment]
Hey Scott,

Yes, of course. Thank you for understanding.

**Comment by ScottON** [comment]
Hey @artemsheludko ,

I hope you had a nice Christmas. I'm wondering if you've got a release date for your theme yet?

Thanks,
Scott

**Comment by artemsheludko** [comment]
Hey @ScottON ,

Thanks, I hope you enjoyed your holiday too.

At the moment, I can't say for sure a release date, I was very busy with the main work. Hopefully, soon I will have enough time to finish the project.

**Comment by ScottON** [comment]
Hey @artemsheludko ,

Thanks for the quick response.

Totally understand. I can postpone setting up my inbound channel a little longer. I'll get all my content prepared so I'm ready for the release. Your theme is EXACTLY how I want my site to look! I'm keeping my fingers crossed that it's released soon ;)

Thanks again!

**Comment by artemsheludko** [comment]
Hey @ScottON,

Finally finished a new portfolio theme. I don't know if this will meet your expectations. In any case, I will share with you the link as I promised - https://jekyllthemes.io/theme/avenco-portfolio-jekyll-theme

Best regards, Artem

**Comment by ScottON** [comment]
Hey @artemsheludko ,

Thanks for remembering 😀

I've just had a look and it looks really good. I think you've added everything I wanted! 

It's not quite as minimalistic as Zolan, but the font and colour should be pretty easy for me to change?

I'm super busy the next few weeks, but I'll get it all set up asap.

Thanks again!!

**Comment by artemsheludko** [comment]
Hey @ScottON,

I'm glad you liked the theme :)

In the process of creating this theme, the design changed several times, this time I wanted to do something modern and at the same time minimalistic. I hope I succeeded.

Yes, you can easily change the colors and fonts, the file structure of the Avenco theme is almost the same as in the Zolan theme.

Have a nice weekend!
